version: "3.3"
services:
  yolodetect:
    build:
      context: './'
    networks:
      - frontend
      - backend
    ports:
      - "49999:80"
    volumes: 
      - ./flask:/home/flask
networks:
  frontend:
  backend:
